HIDDEN_KEYWORDS = [
    "REDACTED FOR PRIVACY",
    "PRIVATE REGISTRATION",
    "PRIVACY PROTECTION",
    "DATA REDACTED",
    "ANONYMOUS",
    "PROXY",
    "Domains By Proxy",
    "WhoisGuard",
    "PrivacyProtect.org",
    "Freenom",
    "Google Domains",
    "Namecheap",
    "GoDaddy",
    "parklogic.com",
    "freenom.com",
    "godaddy.com",
    "namecheap.com",
    "registrar.secureserver.net",
]
